name: Windows CI Test

on: 
  push:
    branches: [main, master]
  pull_requests:
    branches: [main, master]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout Repository and submodules
      uses: actions/checkout@v2
      with: 
        submodules: recursive
    - name: prepare
      run: |
        make prepare
    - name: configure
      run: |
        cmake -S . -B build
    - name: build
      run: |
        cmake --build build --config Debug -j4
    - name: test
      run: |
        cd build
        ctest --build-config Debug
      

      

